services:
  # app:
  #   build: .
  #   ports:
  #     - '5173:5173'
  #   env_file:
  #     - .env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  postgres:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: hex
      POSTGRES_PASSWORD: hexpassword
      POSTGRES_DB: hexdb
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready'"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  pg_data:
