services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: hex
      POSTGRES_PASSWORD: hex
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
